name: Godot Client CI

on:
  push:
    paths:
      - "client-godot/**"
      - ".github/workflows/godot.yml"
  pull_request:
    paths:
      - "client-godot/**"

jobs:
  gdunit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run GdUnit4 tests
        uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: "4.3"
          godot-status: "stable"
          project_dir: "client-godot"
          paths: "res://tests/"
          timeout: 10
